name: personal_agent
description: Private AI agent service using atPlatform, Ollama, and Claude
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # atPlatform SDK for encrypted communication and storage
  at_client: ^3.0.0
  at_lookup: ^3.0.0
  at_commons: ^4.0.0
  at_onboarding_cli: ^1.3.0
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # Environment variables
  dotenv: ^4.2.0
  
  # Logging
  logging: ^1.2.0
  
  # CLI arguments
  args: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.0
  lints: ^3.0.0
